package com.example

unit RuleUnit
// unit com.example.RuleUnit;

import com.example.Person;
import com.example.Res;

rule "Check if minor"
    when
        $res : /res
        $person : /personne[age < 18]
    then
        System.out.println($person.getName() + " is a minor.");
        $res.setMajor(false);
end

rule "Check if adult"
    when
        $res : /res
        $person : /personne[age >= 18]
    then
        System.out.println($person.getName() + " is an adult.");
        $res.setMajor(true);
end

rule "claims"
    when
        $res : /res
        $person : /personne[address str[startsWith] "75012", disaster contains "Incendie" || disaster contains "Inondation"]
    then
        $res.setMontantIndemnisation($person.getMaisonPrice() * 0.6);
end

rule "claims2"
    when
        $res : /res
        $person : /personne[address str[startsWith] "34000", disaster contains "Incendie" || disaster contains "Inondation"]
    then
        $res.setMontantIndemnisation($person.getMaisonPrice() * 0.4);
end