package com.example

unit RuleUnit
// unit com.example.RuleUnit;

import com.example.Person;
import com.example.Res;

rule "Check if minor"
    when
        $res : /res
        $person : /personne[age < 18]
    then
        System.out.println($person.getName() + " is a minor.");
        $res.setMajor(false);
end

rule "Check if adult"
    when
        $res : /res
        $person : /personne[age >= 18]
    then
        System.out.println($person.getName() + " is an adult.");
        $res.setMajor(true);
end